### ISSUE TITLE
Falscher Link zu den Gehäuselagern

### ISSUE THREAD

**Issue by callimero** [heise/MaXYposi#1]
4 Gehäuselager Igus WJ200UM-01-10 (Standard) oder WJUME-01-10 (einstellbares Spiel)

Link zeigt auf Schienen

**Comment by jlegen** [comment]
benutz' einfach die **Suche** auf igus.de; die Schienenbezeichner aus der Stückliste muss man allerdings "übersetzen", damit sie gefunden werden:
"W-10-40"  muss heissen "WS-10-40"
"W-10" muss heissen "WS-10"

**Comment by callimero** [comment]
Erm, klar ich kann suchen, aber den Link zu reparieren geht nicht?
:-)

**Comment by callimero** [comment]
Ah, ok, beknackter Shop. Sorry igus...

Vielleicht gehen die Links aus dem Warenkorb: https://secure.igus.de/myigus/default.aspx?page=addshoppingcartpopup&artno=WJ200UM-01-10

Würde es doch vereinfachen die Sachen schnell "zusammenzuklicken".
