### ISSUE TITLE
GRBL Firmware für ATmega644

### ISSUE THREAD

**Issue by jlegen** [heise/MaXYposi#10]
Das steht da nun so lapidar - heisst das, MaxXYPosi läuft nicht mit dem "normalen" GRBL auf 328? Oder würde "besser laufen" mit was anderem (GRBL für 644)?
Und warum 644 - einen Fork für Atmega2560 gibt's doch auch bereits? 
Leider sind ja entsprechende 644-Boards wohl eher spärlich gesäht...

**Comment by MakeMagazinDE** [comment]
Hallo,

natürlich ist auch ein normaler Arduino-328 mit dem Standard-GRBL geeignet.

Wir haben unser 644-GRBL allerdings auf 4 Achsen erweitert und 32 I/Os hinzugefügt, außerdem ein Handrad- und Joystick-Jog-Anschluss sowie eine Echtzeit-Positionsanzeige mit LDC 16x2 auf einem (optionalen) Bedienfeld. Dazu wird es eine Platine und einen Bausatz geben.

BTW ist ein 2560 für die knapp 40 KByte (mit allen Erweiterungen) doch etwas dick bemessen.

**Comment by jlegen** [comment]
...welche Rolle spielt das, wenn ich zum Preis eines 644-Boards mehr als 3 Atmega2560-Boards bekomme, und das 'an jeder Ecke'? 
Aber schön, dass auch die normale 328-Version tut - bin ja froh, wenn irgenwann mal meine 3 Achsen funktionieren, an eine 4. denk' ich eh' erstmal nicht... ;-)
Und natürlich 'Thumbs up' für dieses schöne Projekt, das mich dank der prima Doku (CAD-Files) endlich mal das lange 'schwelende' Thema CNC hat anpacken lassen...
