### ISSUE TITLE
22mm Siebdruckplatte

### ISSUE THREAD

**Issue by peddi47** [heise/MaXYposi#3]
Die Suche nach solchen Siebdruckplatten landet bei mir immer bei 21mm. Der Unterschied ist gering, aber wo kann man das genannte Maß bekommen?

**Comment by jlegen** [comment]
imo gibt's üblicherweise 22mm MDF, und nur 21mm Siebdruck. Dürfte aber wohl eher egal sein... :)

**Comment by longkeeler** [comment]
Selbst 18mm Siebdruck (oder ist das Standardmaß da 16mm?) dürfte noch hinreichend stabil sein. Allenfalls die Schraubenlängen wären dann anzupassen. Und wenn man die Auffütterungsleisten setzt, wie im Artikel erwähnt, sollten die aus einer Platte geschnitten sein, denn die Fertigungstoleranz kann da sonst schon mal zu perspektivischer Verzerrung führen. 
Bei der Arbeitshöhe sollte man gleich auch an das Einlegen einer Opferschicht, also z.B. einer 5mm MDF-Platte, denken, in die der Fräser hineinfahren kann, ohne das Werkzeug zu zerschraddeln.

**Comment by longkeeler** [comment]
Beim Öffnen der master.rsdoc mäkelt Zeichenfunken hier noch das Fehlen der Schrittmotore an. Allerdigns muß man anerkennen, daß die Dateien heute tagsüber einen gewissen reifegrad erreicht haben. Die rsdoc-Datei auf der Make:-Seite allerdings, also nicht im Github, ist wohl irgendwas, nur kein rsdoc.

**Comment by longkeeler** [comment]
Wenn man die Y-Riemenspanner /-haltger etwas anders anordnet, also weiter in +/-Y verschiebt, gewinnt man noch ein paar wertvolle Zentimeter Verfahrweg. Und für die Erzeugung der Riemensappnung würde ich auch noch einen einstellbaren Spannmechanismus vorsehen, wie von vielen 3D-Druckern geläufig.

**Comment by longkeeler** [comment]
Noch zwei Dinge heute abend: Wenn man schon bei igus bestellt, sollte man auch gleich mal nach deren Energieketten schauen - die sind nicht nur für's Auge, sondern auch für Funktion und Sicherheit optimal.

Und schließlich als Anregung: Das berühmte C.Meyersche Zielmikroskop (USB-Kamera), wenn das mit in die Software eingebunden werden könnte, das wäre super.

**Comment by MakeMagazinDE** [comment]
18, 21 oder 22 sollte egal sein, änder an der Geometrie wenig. Unsere Platten hatten 22.
