### ISSUE TITLE
.rsdoc

### ISSUE THREAD

**Issue by turaluralu** [heise/MaXYposi#8]
Hallo,
gibt es eine Möglichkeit .rsdoc Files unter Linux oder MacOS zu öffnen?
Windows habe ich leider (oder Gott sei Dank?) nicht und würde auch ungern eine Lizenz für teuer Geld erstehen wollen nur um  Designspark Mechanical 2.0 betreiben zu können.
:-)

**Comment by MakeMagazinDE** [comment]
Leider nein. Evt. gelingt uns ein STEP-Export. Umfangreichen Datenaustausch gestattet leider nur die kommerzielle Version von SpaceClaim, die uns mit rund 5000 Euro aber auch zu teuer ist...

**Comment by turaluralu** [comment]
schade :-(
